In [9]:
import numpy as np
l=[[1,2,3],[4,5,6],[7,8,9]]

mat = np.array(l)

r1=mat[0:3,0:3]
r2=mat[0:2,0:2]
print(r1)
print(r2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [12]:
import numpy as np
l=[[1,2,3],[4,5,6],[7,8,9]]

mat = np.array(l)

r1=mat[0:2,0:2]
r2=mat[1:3,1:3]
print(r1)
print(r2)

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


In [20]:
#reshaping
import numpy as np
l=[[1,2,3],[4,5,6]]
mat = np.array(l)
ar=mat.reshape(3,2)
print(ar)


[[1 2]
 [3 4]
 [5 6]]


In [42]:
import numpy as np

ar= np.ones(5)
print(ar)

[1. 1. 1. 1. 1.]


In [43]:
import numpy as np


l= np.zeros(3)
print(ar)

[1. 1. 1. 1. 1.]


In [37]:
import numpy as np

ar= np.eye(4,4)
print(ar)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [39]:
import numpy as np

ar= np.diag([1,2,3])
print(ar)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [41]:
import numpy as np

ar= np.random.randint(1,10,4)
print(ar)

[3 6 6 1]


In [46]:
import numpy as np

ar= np.random.rand(2,3)
print(ar)

[[0.77225241 0.06071949 0.1589539 ]
 [0.80956505 0.79488448 0.08756461]]


In [47]:
#slice array(sa)
import numpy as np
l=[[1,2,3,4,5,6]]
mat = np.array(l)

sa=mat[2:4].copy()
sa[:]=0
print(sa)
print(mat)

[]


In [48]:
import numpy as np

mat = np.arange(1,11)
print(mat)

[ 1  2  3  4  5  6  7  8  9 10]


In [51]:
import numpy as np

mat = np.arange(1,11)
print(mat)
m=mat>5

print(m)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]


In [52]:
ar = np.array([1,2,3,4,5,6])
ar*3

array([ 3,  6,  9, 12, 15, 18])

In [53]:
ar**2

array([ 1,  4,  9, 16, 25, 36])